/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "CopyLeft": "HostsWidget\nV2.0 (Oct. 2009)",
    "disclaimer": "This widget alters the permissions on your /etc/hosts file. If you do not feel comfortable with this or do not know what this means, delete this widget immediately. ",
    "Disclaimer": "This widget alters the permissions on your /etc/hosts file. If you do not feel comfortable with this or do not know what this means, delete this widget immediately. ",
    "Done": "Done",
    "Hello, World!": "Hello, World!",
    "Permissions": "",
    "Version": "HostsWidget\nV2.0 (Oct. 2009)"
};



